name: Build Fence Calculator Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --add-data "prices.xlsx;." fence_calculator.py

      - name: Archive artifacts
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path dist_artifacts
          Copy-Item -Path dist\fence_calculator.exe -Destination dist_artifacts\
          Compress-Archive -Path dist_artifacts -DestinationPath fence_calculator_artifacts.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # ИСПРАВЛЕНО
        with:
          name: fence-calculator-exe
          path: fence_calculator_artifacts.zip
